### ISSUE TITLE
Behavior when replacing "more info".

### ISSUE THREAD

**Issue by silfax** [alexarch21/history-explorer-card#126]
History info panel enabled. If I select a different entity from the "Related" tab, I still get the chart for the originally selected entity.

**Comment by teskanoo** [comment]
Thanks for addressing this - much appreciated :)

**Comment by alexarch21** [comment]
Fixed in V1.0.44.

**Comment by silfax** [comment]
installed latest version (1.0.44), cleared cache, switched to different browser, switched to different device, same behavior. if i select an entity from the "related entities" tab, i still get the original entity chart. name and current value of the new entity are shown correctly. two screenshots as example: temperature graph, related entities, select humidity, chart stays the same:
![image](https://user-images.githubusercontent.com/65038681/221279077-2324bbd6-48f7-4541-8108-7d4868596c6b.png)
![image](https://user-images.githubusercontent.com/65038681/221279199-08b2fe45-9227-4838-a569-6d1f8bd93cd9.png)

**Comment by alexarch21** [comment]
You did not properly update, you are still using 1.0.43 (there is no lock icon on the graph, which is new in 1.0.44). Make sure all your caches are properly cleared. Check the version on the console.

**Comment by silfax** [comment]
sorry, it works now. thanks! something went wrong with the update i guess, although hacs was showing v1.0.44. a re-download fixed it. thanks again!
