### ISSUE TITLE
Language selection?

### ISSUE THREAD

**Issue by RobertoCravallo** [alexarch21/history-explorer-card#97]
First of all: THANK YOU! What a cool tool!

It looks like the language setting in HA is not supported / ignored. "not_home" should be "Abwesend". Is there a work-around for that? "not_home" is just not "pretty" or german...  ;-)

Regards from Mannheim, Germany

![IdAW – Home Assistant 2022-11-21 09-48-05](https://user-images.githubusercontent.com/112649622/203006316-77dde3f4-eef1-4f38-9639-44d94b804c3a.jpg)

**Comment by alexarch21** [comment]
You need to turn on state translation, as described in the [readme here](https://github.com/alexarch21/history-explorer-card#timeline-charts).
```
stateTextMode: auto   # Show the automatically translated device class dependent state names
```

**Comment by alexarch21** [comment]
No worries, the available features can be a bit overwhelming.

Viele Grüße nach Mannheim aus Frankreich :)

**Comment by RobertoCravallo** [comment]
Hi Alex,

shouldn't the text in the tool-tip change also?   ;-)

**Comment by alexarch21** [comment]
Yes it should ! And it's fixed in V1.0.38 :)

**Comment by RobertoCravallo** [comment]
Thank you Alex for your efforts!

**Comment by RobertoCravallo** [comment]
Ups, still not quite right.... That should be "für" and not the english "for".  ;-)

![Monosnap 2022-11-28 18-43-39](https://user-images.githubusercontent.com/112649622/204345763-0d7d56b8-d253-4557-82e8-171daff89353.jpg)
